==Исключительные ситуации== - нештатные ситуации работы программы. Обработка этих ситуаций есть борьба за стабильность ПО.
Под надёжностью программного обеспечения - относительно длительное получение бессбойных результатов.

Инструменты для обработки исключений:
1. `assert` (assertion - проверка утверждений) - используется для организации контрольных точек;
2. `signal.h` - библиотека сигналов, которая позволяет бороться с внештатными ситуациями путём получения базовых исключений;
3. `try` `throw` `catch`
Эти инструменты следует использовать только для обработки возможных внештатных ситуаций.
##### assert

`void assert(bool выражение)` - представляет собой макрокоманду с параметрами.

Вся программа - последовательность операторов. Перед тем оператором или вызовом, в котором может произойти внештатная ситуация устанавливается контрольная точка (проверка предусловия). Также контрольная точка может быть установлена после оператора или вызова (проверка постусловия). 

Пример:
```
class Vect {
private:
	int *p;
	int size;
public:
	Vect(int);
}

Vect::Vect(int n) {
	size = n;
	assert(size > 0);
	p = new int[size];
	assert(p != nullptr);
}
```
Контрольные точки позволяют вызвать останов программы при неверных данных, но при этом не даёт возможности возобновить программу. Также вызов этой команды не предполагает вывод какого-либо сообщения об ошибке.
##### signal.h

`#include <signal.h>`
Библиотека предоставляет стандартный интерфейс для простой обработки исключений, определяемых самой системой исключений.

> `#define` - определение макрокоманд. Пример: `#define PI 3.1415926`, `#define cube(x) x*x*x`. Аналогом макрокоманд является `inline` функции.

В библиотеке есть набор макрокоманд:
- `#define SIGINT 2` - сигнал прерывания;
- `#define SIGFPE 8` - сигнал исключения с плавающей точкой;
- `#define SIGBRT 22` - сигнал аварийного завершения программы;
- ...
набор функций:
- `raise(сигнал)` - функция для вызова ручного вызова сигнала;
- `signal(сигнал, своя функция)` - связывает конкретный сигнал с функцией для его обработки.

##### try throw catch

Пробный блок:
```
// обычный ход программы
try {
	// операторы с возможной внештатной ситуацией
}
```

`throw(выражение исключения (+тип))` - "запустить" обработчик исключений (вызвать исключение).

`catch(тип исключения)` - функция без возвращаемого типа с параметром типа перехватываемого исключения. Эта функция предназначена для борьбы с внештатной ситуацией (выполнится как только блоком try будет поймано исключение).

Пример:
```
int x, y;
try {
	x = a + b;
	y = a - b;
	if (x > y) throw(x+y);
	...
} catch (int) {
	...
}
```
